=== cr0t/lexin/experiments/LexinSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="indexType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="prefix"/>
      <xs:enumeration value="suffix"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="referenceType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="animation"/>
      <xs:enumeration value="compare"/>
      <xs:enumeration value="phonetic"/>
      <xs:enumeration value="see"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="Compound" nillable="true">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="Inflection" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="MatchingID" type="xs:string"/>
      <xs:attribute name="Description" type="xs:string"/>
      <xs:attribute name="ID" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Derivation" nillable="true">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="Inflection" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Description" type="xs:string"/>
      <xs:attribute name="ID" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Example" nillable="true">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="MatchingID" type="xs:string"/>
          <xs:attribute name="ID" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Idiom" nillable="true">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="MatchingID" type="xs:string"/>
          <xs:attribute name="ID" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Antonym">
    <xs:complexType>
      <xs:attribute name="Value" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Dictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Word" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BaseLang" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Meaning" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="MatchingID" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="Reference" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="MatchingID" type="xs:string"/>
                        <xs:attribute name="TYPE" type="referenceType" use="required"/>
                        <xs:attribute name="VALUE" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>

                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element name="Comment" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="MatchingID" type="xs:string"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>

                      <xs:element name="Explanation" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="MatchingID" type="xs:string"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>

                      <xs:element name="Alternate" type="xs:string" minOccurs="0" maxOccurs="1"/>

                      <xs:element ref="Antonym" minOccurs="0" maxOccurs="unbounded"/>

                      <xs:element name="Usage" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="MatchingID" type="xs:string"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>

                    <xs:element name="Phonetic" nillable="true" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="File" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="Illustration" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="TYPE" type="xs:string" use="required"/>
                        <xs:attribute name="VALUE" type="xs:string" use="required"/>
                        <xs:attribute name="Norlexin" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="Inflection" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="Variant" nillable="true" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="Description" type="xs:string"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="Graminfo" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element ref="Example" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="Idiom" minOccurs="0" maxOccurs="unbounded"/>

                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element ref="Compound" minOccurs="0" maxOccurs="1"/>
                      <xs:element ref="Derivation" minOccurs="0" maxOccurs="1"/>
                    </xs:choice>

                    <xs:element name="Index" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="Value" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="indexType"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="TargetLang" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Translation" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Synonym" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Explanation" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element ref="Antonym" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="Example" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="Idiom" minOccurs="0" maxOccurs="unbounded"/>

                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element ref="Compound" minOccurs="0" maxOccurs="1"/>
                      <xs:element ref="Derivation" minOccurs="0" maxOccurs="1"/>
                    </xs:choice>
                  </xs:sequence>

                  <xs:attribute name="Comment" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>

            <xs:attribute name="MatchingID" type="xs:string"/>
            <xs:attribute name="Value" type="xs:string" use="required"/>
            <xs:attribute name="Variant" type="xs:string"/>
            <xs:attribute name="Type" type="xs:string" use="required"/>
            <xs:attribute name="ID" type="xs:string" use="required"/>
            <xs:attribute name="VariantID" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

      <xs:attribute name="BaseLang" type="xs:string" use="required"/>
      <xs:attribute name="TargetLang" type="xs:string" use="required"/>
      <xs:attribute name="Version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cr0t/lexin/test/fixtures/dictionaries/swe_eng.xml
<?xml version='1.0' encoding='UTF-8'?>
<Dictionary BaseLang="Swedish" TargetLang="English" Version="2010-04-04" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lexin.nada.kth.se/schema/LexinSchema.xsd">
  <Word ID="1" MatchingID="3" Type="prep." Value="à" Variant="1" VariantID="1">
    <BaseLang>
      <Meaning MatchingID="9011002">till ett pris av</Meaning>
      <Comment>endast vid sifferuttryck</Comment>
      <Phonetic File="v2/100052_1.mp3">a</Phonetic>
      <Example ID="1" MatchingID="1174820">två koppar kaffe à 8 kronor (styck)</Example>
      <Index Value="à" />
    </BaseLang>
    <TargetLang>
      <Translation>at</Translation>
      <Synonym>at a price of</Synonym>
      <Comment>used only with numerical expressions</Comment>
      <Example ID="1">two cups of coffee at 8 kronor (each)</Example>
    </TargetLang>
  </Word>
  <Word ID="1" MatchingID="4" Type="prep." Value="à" Variant="1" VariantID="2">
    <BaseLang>
      <Meaning MatchingID="9011003">till</Meaning>
      <Comment>i sifferuttryck</Comment>
      <Phonetic File="v2/100052_1.mp3">a</Phonetic>
      <Example ID="2" MatchingID="1174824">2 à 3 meter</Example>
      <Index Value="à" />
    </BaseLang>
    <TargetLang>
      <Translation>to</Translation>
      <Comment>in numerical expressions</Comment>
      <Example ID="2">2 to 3 metres</Example>
    </TargetLang>
  </Word>
  <Word ID="2" MatchingID="1" Type="subst." Value="a" Variant="2" VariantID="3">
    <BaseLang>
      <Meaning MatchingID="9011000">första bokstaven i alfabetet</Meaning>
      <Phonetic File="v2/100021_1.mp3">a:</Phonetic>
      <Idiom ID="1" MatchingID="1000010">har man sagt a får man också säga b ("har man börjat får man fortsätta")</Idiom>
      <Idiom ID="2" MatchingID="1000008">a och o ("det viktigaste")</Idiom>
      <Index Value="a" />
    </BaseLang>
    <TargetLang>
      <Translation>a</Translation>
      <Synonym>the first letter of the alphabet</Synonym>
      <Idiom ID="1">in for a penny, in for a pound ("what you start you must finish off")</Idiom>
      <Idiom ID="2">alpha and omega</Idiom>
    </TargetLang>
  </Word>
  <Word ID="2" MatchingID="2" Type="subst." Value="a" Variant="2" VariantID="4">
    <BaseLang>
      <Meaning MatchingID="9011001">sjätte tonen i C-durskalan</Meaning>
      <Comment>musikterm</Comment>
      <Phonetic File="v2/100021_1.mp3">a:</Phonetic>
      <Index Value="a" />
    </BaseLang>
    <TargetLang>
      <Translation>A</Translation>
      <Synonym>the sixth tone in the scale of C major</Synonym>
      <Comment>a musical term</Comment>
    </TargetLang>
  </Word>
  <Word ID="3" MatchingID="64" Type="adv." Value="a conto" Variant="" VariantID="5">
    <BaseLang>
      <Meaning MatchingID="9011060">i förskott</Meaning>
      <Phonetic File="v2/850907_1.mp3">akÅn:to</Phonetic>
      <Index Value="a conto" />
    </BaseLang>
    <TargetLang>
      <Translation>on account</Translation>
      <Synonym>in advance</Synonym>
    </TargetLang>
  </Word>
  <Word ID="1713" MatchingID="2117" Type="subst." Value="bil" Variant="" VariantID="1858">
    <BaseLang>
      <Meaning>ett slags motordrivet fordon</Meaning>
      <Phonetic File="v2/118746_1.mp3">bi:l</Phonetic>
      <Illustration Norlexin="page=17&amp;subpage=2" TYPE="picture" VALUE="17/bil1.swf" />
      <Illustration Norlexin="page=16&amp;subpage=1" TYPE="picture" VALUE="16/stad1.swf" />
      <Inflection>bilen</Inflection>
      <Inflection>bilar</Inflection>
      <Example ID="1208">åka bil</Example>
      <Compound ID="687" MatchingID="8015599">bil|trafik
        <Inflection>bil|trafiken</Inflection>
      </Compound>
      <Compound ID="688" MatchingID="1015425">personbil</Compound>
      <Compound ID="689" MatchingID="1015418">bil|buren</Compound>
      <Compound ID="690" MatchingID="1015419">bil|fri</Compound>
      <Compound ID="691">bil|sjuk</Compound>
      <Compound ID="692">bil|sjuka</Compound>
      <Compound ID="693">bil|telefon</Compound>
      <Compound ID="694" MatchingID="8024302">lastbil</Compound>
      <Index Value="bil" />
      <Index Value="biltrafik" />
      <Index Value="biltrafiken" />
      <Index Value="personbil" />
      <Index Value="bilburen" />
      <Index Value="bilfri" />
      <Index Value="bilsjuk" />
      <Index Value="bilsjuka" />
      <Index Value="biltelefon" />
      <Index Value="lastbil" />
      <Index Value="bilen" />
      <Index Value="bilar" />
      <Index Value="bil" type="prefix" />
      <Index Value="bil" type="suffix" />
      <Index Value="buren" type="suffix" />
      <Index Value="fri" type="suffix" />
      <Index Value="person" type="prefix" />
      <Index Value="sjuk" type="suffix" />
      <Index Value="sjuka" type="suffix" />
      <Index Value="telefon" type="suffix" />
      <Index Value="trafik" type="suffix" />
      <Index Value="trafiken" type="suffix" />
    </BaseLang>
    <TargetLang>
      <Translation>car, motorcar, (automobile [US]), (auto [US])</Translation>
      <Example ID="1208">go by car</Example>
      <Compound ID="687">motor traffic</Compound>
      <Compound ID="688">passenger car</Compound>
      <Compound ID="689">motorized</Compound>
      <Compound ID="690">free of cars</Compound>
      <Compound ID="691">carsick</Compound>
      <Compound ID="692">carsickness</Compound>
      <Compound ID="693">car phone</Compound>
  <Compound ID="694">lorry, (truck [US])</Compound>
    </TargetLang>
  </Word>
  <Word ID="858" MatchingID="1057" Type="subst." Value="avgas" Variant="" VariantID="918">
    <BaseLang>
      <Meaning MatchingID="9012012">gas som bildas vid förbränning i motor</Meaning>
      <Usage MatchingID="1007502">mest i plural</Usage>
      <Phonetic File="v2/109493_1.mp3">²A:vga:s</Phonetic>
      <Inflection>avgasen</Inflection>
      <Inflection>avgaser</Inflection>
      <Example ID="599" MatchingID="1007504">trafiken medför buller och avgaser</Example>
      <Compound ID="391" MatchingID="1007508">bilavgaser</Compound>
      <Compound ID="392" MatchingID="1007505">avgas|rening
        <Inflection>avgas|reningen</Inflection>
      </Compound>
      <Compound ID="393" MatchingID="1007507">avgas|system
        <Inflection>avgas|systemet</Inflection>
      </Compound>
      <Compound ID="394" MatchingID="1007506">avgas|rör</Compound>
      <Index Value="avgas" />
      <Index Value="bilavgaser" />
      <Index Value="avgasrening" />
      <Index Value="avgasreningen" />
      <Index Value="avgassystem" />
      <Index Value="avgassystemet" />
      <Index Value="avgasrör" />
      <Index Value="avgasen" />
      <Index Value="avgaser" />
      <Index Value="avgas" type="prefix" />
      <Index Value="avgaser" type="suffix" />
      <Index Value="bil" type="prefix" />
      <Index Value="rening" type="suffix" />
      <Index Value="reningen" type="suffix" />
      <Index Value="rör" type="suffix" />
      <Index Value="system" type="suffix" />
      <Index Value="systemet" type="suffix" />
    </BaseLang>
    <TargetLang>
      <Translation>exhaust (gas)</Translation>
      <Synonym>the waste gas produced by internal combustion engines</Synonym>
      <Example ID="599">traffic causes noise and pollution</Example>
      <Compound ID="391">exhaust fumes</Compound>
      <Compound ID="392">exhaust conversion, exhaust emission control</Compound>
      <Compound ID="393">exhaust system</Compound>
      <Compound ID="394">exhaust pipe</Compound>
    </TargetLang>
  </Word>
</Dictionary>

=== cr0t/lexin/test/fixtures/dictionaries/swe_rus.xml
<?xml version='1.0' encoding='UTF-8'?>
<Dictionary BaseLang="Swedish" TargetLang="Russian" Version="2010-07-07" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lexin.nada.kth.se/schema/LexinSchema.xsd">
  <Word ID="1" MatchingID="3" Type="prep." Value="à" Variant="1" VariantID="1">
    <BaseLang>
      <Meaning MatchingID="9011002">till ett pris av</Meaning>
      <Comment>endast vid sifferuttryck</Comment>
      <Phonetic File="v2/100052_1.mp3">a</Phonetic>
      <Example ID="1" MatchingID="1174820">två koppar kaffe à 8 kronor (styck)</Example>
      <Index Value="à" />
    </BaseLang>
    <TargetLang>
      <Translation>по</Translation>
      <Comment>"только с цифрой"</Comment>
      <Example ID="1">две чашки кофе по 8 крон (kaждая)</Example>
    </TargetLang>
  </Word>
  <Word ID="1" MatchingID="4" Type="prep." Value="à" Variant="1" VariantID="2">
    <BaseLang>
      <Meaning MatchingID="9011003">till</Meaning>
      <Comment>i sifferuttryck</Comment>
      <Phonetic File="v2/100052_1.mp3">a</Phonetic>
      <Example ID="2" MatchingID="1174824">2 à 3 meter</Example>
      <Index Value="à" />
    </BaseLang>
    <TargetLang>
      <Translation>до</Translation>
      <Comment>"с цифрой"</Comment>
      <Example ID="2">от 2 до 3 метров</Example>
    </TargetLang>
  </Word>
  <Word ID="2" MatchingID="1" Type="subst." Value="a" Variant="2" VariantID="3">
    <BaseLang>
      <Meaning MatchingID="9011000">första bokstaven i alfabetet</Meaning>
      <Phonetic File="v2/100021_1.mp3">a:</Phonetic>
      <Idiom ID="1" MatchingID="1000010">har man sagt a får man också säga b ("har man börjat får man fortsätta")</Idiom>
      <Idiom ID="2" MatchingID="1000008">a och o ("det viktigaste")</Idiom>
      <Index Value="a" />
    </BaseLang>
    <TargetLang>
      <Translation>А</Translation>
      <Idiom ID="1">если сказал А, говори и Б (если начал, то доведи до конца)</Idiom>
      <Idiom ID="2">от альфы до омеги (от начала до конца)</Idiom>
    </TargetLang>
  </Word>
  <Word ID="2" MatchingID="2" Type="subst." Value="a" Variant="2" VariantID="4">
    <BaseLang>
      <Meaning MatchingID="9011001">sjätte tonen i C-durskalan</Meaning>
      <Comment>musikterm</Comment>
      <Phonetic File="v2/100021_1.mp3">a:</Phonetic>
      <Index Value="a" />
    </BaseLang>
    <TargetLang>
      <Translation>ля</Translation>
      <Comment>"музыкальный термин (шестая нота гаммы)"</Comment>
    </TargetLang>
  </Word>
  <Word ID="3" MatchingID="64" Type="adv." Value="a conto" Variant="" VariantID="5">
    <BaseLang>
      <Meaning MatchingID="9011060">i förskott</Meaning>
      <Phonetic File="v2/850907_1.mp3">akÅn:to</Phonetic>
      <Index Value="a conto" />
    </BaseLang>
    <TargetLang>
      <Translation>А-конто</Translation>
      <Synonym>на мой счёт</Synonym>
    </TargetLang>
  </Word>
</Dictionary>
